[book]
authors = ["Fuel Labs <contact@fuel.sh>"]
language = "en"
multilingual = false
src = "src"
title = "Fuel Specifications"

[output.html]
git-repository-url = "https://github.com/FuelLabs/fuel-specs"
